### ISSUE TITLE
[CONTENT] Creating NFTs

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#43]
This issue is for drafting content for the following:
- Title: Creating NFTs
- Address: `/how-to/creating-nfts/`

**This content is slated for MVP, but might not be included in 20 May round.**

**Comment by jessicaschilling** [comment]
@yusefnapora and @johndmulhausen -- per our sync discussion, can you both please discuss and determine next steps surrounding ...
- What we already covered of this content in the end-to-end tutorial
- What we should be replacing this issue with: some number of more specific how-tos (i.e. how you could implement a royalty scheme, etc)

If we could determine what we're doing instead by mid-week, in order to get started on that replacement content, that would be great. Thank you!

**Comment by yusefnapora** [comment]
@johndmulhausen and I discussed this a bit yesterday. Basically we think that packaging up the minting mechanic from the end-to-end experience as a "how to" style article is valuable, but we should wait until we have an example for another blockchain to contrast with. Otherwise we're just repeating ourselves, which is fine but not worth the investment while there's so much else to do.

So, we want to write a how-to guide on "lazy minting", which seems like a topic that's valuable, not too complex, and fits well into the how-to format.

After that, we can do a minting how-to with another blockchain (maybe Flow), and reframe some of the e2e example as our Ethereum how-to so we can contrast them.

**Comment by jessicaschilling** [comment]
@yusefnapora @johndmulhausen Sounds like a plan. Are you OK if I do the following?
1. Close this issue
2. Replace it with two new issues for how-to content: lazy minting and minting on different blockchains
3. Replace the "Creating NFTs" link in the left nav with those two new topics (marked as "under construction"):
![image](https://user-images.githubusercontent.com/1507828/122096384-bd205500-cdcb-11eb-84da-f985a877709f.png)

**Comment by yusefnapora** [comment]
@jessicaschilling sounds great to me

**Comment by jessicaschilling** [comment]
Superseded by https://github.com/protocol/nft-website/issues/97 and https://github.com/protocol/nft-website/issues/98.
